image: python:3.10-alpine

stages:
  - code-analyze
  - test

isort:
  stage: code-analyze
  script:
    - pip install -r requirements.txt
    - pip install isort
    - isort . --check-only
  allow_failure: true
#  only:


black:
  stage: code-analyze
  script:
    - pip install -r requirements.txt
    - pip install black
    - black . --check --verbose --diff --color
  allow_failure: true

flake8:
  stage: code-analyze
  script:
    - pip install -r requirements.txt
    - pip install flake8
    - flake8 .
  allow_failure: true

pylint:
  stage: code-analyze
  script:
    - pip install -r requirements.txt
    - pip install pylint
    - find . -name "*.py" -exec pylint {} \;
  allow_failure: true

test-docker:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  script:
    - docker build .
#  only:
#    - merge_requests
#    - master