build-job:
#  image: ubuntu:20.04
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!, docker-compose up"
    - docker build

test-job1:
  stage: test
  script:
    - echo "ADD TEST FOR API"

test-job2:
  stage: test
  script:
    - echo "TEST FOR docker-compose"
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - docker-compose up -d
    - sleep 30
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - docker-compose down 

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch. DOCKER"
#    - docker pull
