image: python3.10
before_script:
  - pip install -r requirements.txt
  - pip install isort, black, flake8, pylint
stages:
  - code-analyze

isort:
  stage: code-analyze
  script:
    - ls -la
    - isort . --check-only
  only:


black:
  stage: code-analyze
  script:
    - black . --check --verbose --diff --color

flake8:
  stage: code-analyze
  script:
    - flake8 .

pylint:
  stage: code-analyze
  script:
    - find . -name "*.py" -exec pylint {} \;

test-docker:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  script:
    - docker build .
  only:
    - merge_requests
    - master