image: docker
before_script:
  - echo "START"
  - docker info
#rules:
#  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


build-job:
  stage: build
  script:
    - echo "build docker image"
    - docker build .
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


test-job1:
  stage: test
  script:
    - echo "ADD TEST FOR API"
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


test-job2:
  stage: test
  script:
    #- echo "TEST FOR docker-compose"
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    #- docker-compose up -d
    - sleep 30
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    #- docker-compose down 
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch. DOCKER"
#    - docker pull
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
