build-job:
  image: alpine
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!, docker-compose up"

test-job1:
  stage: test
  script:
    - echo "ADD TEST FOR API"

test-job2:
  stage: test
  script:
    - echo "ADD TEST FOR DOCKER"
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch. DOCKER"`
