before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - docker info

build-job:
  stage: build
  script:
    - echo "build docker image"
    - docker build .


deploy_dev:
  stage: deploy
  script:
    - docker compose up -d --build
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
  tags:
    - dev-runner


deploy_master:
  stage: deploy
  script:
    - docker compose up -d --build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  tags:
    - master-runner
