image: docker
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'

  - eval $(ssh-agent -s)
  - echo "$SSH_YUUMI" | tr -d '\r' | ssh-add -

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - ssh-keyscan -p 22760 yuumi.skni.umcs.pl >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - docker info 
#  - ssh -p 22760 inventary-gitlab@yuumi.skni.umcs.pl "git clone ssh://git@git.skni.umcs.pl:2794/jan.bylina/inventaryapi.git"



build-job:
  stage: build
  script:
    - echo "build docker image"
    - docker build .
    - ssh -p 22760 inventary-gitlab@yuumi.skni.umcs.pl "cd ~/inventaryapi && git pull && docker-compose down"
    - ssh -p 22760 inventary-gitlab@yuumi.skni.umcs.pl "cd ~/inventaryapi && docker build . && docker-compose up -d"
    - sleep 2



test-job1:
  stage: test
  script:
    - echo "ADD TEST FOR API"



test-job2:
  stage: test
  script:
    #- echo "TEST FOR docker-compose"
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    #- docker-compose up -d
    - sleep 30
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    #- docker-compose down 

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch. DOCKER"
#    - docker pull

