version: '3.0'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    container_name: inventaryAPI
    # environment:

    volumes:
      - .:/code
    restart: always
    networks:
      - back
    # depends_on:
    #   - db
networks:
    back:

