version: '3.0'

volumes:
  db_data:

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=inventary
      - MYSQL_USER=inventary
      - MYSQL_PASSWORD=inventary
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 10s
            retries: 10
    ports:
     - "3306:3306"
    volumes:
     - db_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "8555:8555"
    container_name: inventaryAPI
    volumes:
      - .:/code:ro
    restart: always
    depends_on:
      db:
        condition: service_healthy
